### ISSUE TITLE
Arduino と センサ部とのインターフェイス設計

### ISSUE THREAD

**Issue by SakaiYuki** [GS05-43-MatsumuraYu/kadai#1]

**Comment by SakaiYuki** [comment]
@GS05-43-MatsumuraYu 

アットマーク付きでコメント書けばメール飛ぶよね？のテスト

**Comment by GS05-43-MatsumuraYu** [comment]
おととい電話で話をしていた本に実例の資料(PDF)を置きます。

参考資料：Arduinoで計る，測る，量る
　P241　11-8　ストレイン・ゲージによる重さの測定
参考URL:http://shop.cqpub.co.jp/hanbai/books/42/42191.html

[Arduinoで計る，測る，量る.pdf](https://github.com/GS05-43-MatsumuraYu/kadai/files/561047/Arduino.pdf)

**Comment by SakaiYuki** [comment]
ありがとう！

今考えているプランだと、キッチンスケールの中にも Arduino のメインマイコン相当の IC が入っていると思われ、
その IC の AD 変換機能を使っていると予想しています。

AD 変換ポートの外部の増幅回路はキッチンスケールにも入っていると思われ、それを利用できないか、調査するのが 11/5 の作業になると思います。

現時点での仮設計では、「Arduino と センサ部とのインターフェイス」は、
- 1. GND
- 2. signal (analog voltage)
- 3. Vcc

の 3 線の想定です。その設計で正しいかどうかの確認 (at 11/5 ) のために必要な道具は
- [x] 生贄となるキッチンスケール（購入？）
- [x] ドライバー（持っています）
- [x] テスター（数千円のポケットテスターで十分）
- [x] ブレッドボードの配線 or ワニ口クリップ配線
- [x] 紙とペン（回路の解析結果を書く）

で、キッチンスケールを解析した結果、部品や回路の追加・交換などが必要な場合は、以下はんだごて一式
- [ ] はんだごて
- [ ] はんだ
- [ ] こて台
- [ ] はんだ吸い器 (optional)
- [x] ピンセット（持っています）
- [ ] 必要な部品

**Comment by SakaiYuki** [comment]
@GS05-43-MatsumuraYu 

Arduino のチュートリアルか何かで、「アナログ入力」（ AD 変換など、別の名前の可能性もあります）について資料があれば持ってきてください！

ハードウェアの仕様に関しては、 Arduino 本体（またはその品番だけでも）があれば、チップ名から、資料を探して調べますが、実際にソフトウェア側でどうやって取り込めるか、は資料があると助かります。

## 例（このまま使えるかどうかは分かりませんが…）

http://www.musashinodenpa.com/arduino/ref/index.php?f=2&pos=116

http://qiita.com/nyagato_00/items/2937a11630109a3db6e1

**Comment by GS05-43-MatsumuraYu** [comment]
生贄となるキッチンスケール（購入？）
→購入済

 ドライバー（持っています）→頼みます

 テスター（数千円のポケットテスターで十分）
→昨日メルカリで注文。早ければ週末届く

 ブレッドボードの配線 or ワニ口クリップ配線
→ジャンパワイヤというはんだごてなしで、つなげれる配線はあり。ワニ口クリップはない。買うべき？

 紙とペン（回路の解析結果を書く）→ある。

**Comment by SakaiYuki** [comment]
> ジャンパワイヤ

それです！ただ、ブレッドボードみたいな「穴」がないと手を離して固定できないので、

> ワニ口クリップ

は、ほぼ必須です。ホームセンターでも売っていますがやや大きめだと思います。今回の事例だと小ぶりなものがあると便利です。

**Comment by GS05-43-MatsumuraYu** [comment]
100キンにも売っている？と聞いたー
ジャンパワイヤがあれば、配線はいらんねんな？

**Comment by SakaiYuki** [comment]
ジャンパワイヤでは、ブレッドボードみたいな「穴」がないと手を離して固定できないので、実際の基板（今回はキッチンスケール）を相手にするときは役に立たないので、ワニ口（みのむし）クリップがあると、作業が捗ります。

なくても、苦労はするけれど何もできないことはないけど…

100きんだと大きいものになってしまうので、秋葉原なら現地調達でも可！

**Comment by GS05-43-MatsumuraYu** [comment]
![img_3619](https://cloud.githubusercontent.com/assets/21537574/19956378/38c65db8-a1cf-11e6-8419-4fa293537cfd.JPG)

ホームセンターでワニ口クリップ買いましたが、でかい？

**Comment by SakaiYuki** [comment]
でかい！でかいなーｗ

すんません、ほしいのはこんなんでした…

http://akizukidenshi.com/catalog/g/gC-04352/

**Comment by GS05-43-MatsumuraYu** [comment]
明日どうするー?
DMM.makeを使う場合だとDrop-in会員になる必要があって、そのためには1時間のガイダンスを受けなければいけない。
https://akiba.dmm-make.com/about/plan
秋月商店の開店時間は11:30～で、場所は以下の通り。
http://akizukidenshi.com/catalog/contents2/akiba.aspx

明日はラボを使わず、部品の集めして、カフェで設計の打合せにするー?
おれも15:00時くらいに出ないといけないし。。

**Comment by SakaiYuki** [comment]
ばらしたりする時は、場所はここかな！

http://assemblage.tokyo/faq/ (10:00〜18:00)

以下は午後からしかやってなかった…

http://nanolab.jp/service (土日祝：13:00-20:30)

いったんばらしてやることやって、後は打ち合わせだけとなったらカフェに移動しましょー（カフェなら飲み物代だけで居続けられるだろうから）

**Comment by GS05-43-MatsumuraYu** [comment]
おーっよく見つけたなぁー
アクセス方法見てもよくわからんかったし、電気街口改札に10:30集合でいいー?
http://assemblage.tokyo/faq/ (10:00〜18:00)

**Comment by SakaiYuki** [comment]
> 電気街口改札に10:30集合

了解！ 👍

**Comment by GS05-43-MatsumuraYu** [comment]
gsアカデミーの課題ではここまで作った！
お題が読書に関するサービスだったから、読書量計算だけど、これを調味料にするつもり。
http://spice-shelf.jp/spice-shelf/

**Comment by GS05-43-MatsumuraYu** [comment]
次回打合わせ時日程もこちら書きます。skypeは気づきにくいので

平日夜でもOKです！
一昨日の行ったところは18:00までだから、行くならナノラボだけど、 (平日：13:00-20:30　定休日：月曜日)です。19時に＠ナノラボ着くらいでいけるけど、下記日程どうでしょ?

　・11月11日(金)
　・11月15日(火)

実質1時間くらいしか作業できないからもっと遅くまでやっているところも探してみます(秋葉原にこだわらず)。

どこかしってる?

**Comment by SakaiYuki** [comment]
新宿・渋谷方面だとアクセスがつらいので、東部、千葉方面で探してみた

https://fabcross.jp/topics/fabnavi/20150609_fabnavi_20.html ( https://fabcross.jp/list/series/fabnavi/ や http://fablabjapan.org/2014/12/07/post-5356/ より）

あと、「コワーキングスペース」という視点で、モノ志向なとこがあるといいんだよね。  ( Halake っというとこもあるけど、埼玉なので遠いね https://www.facebook.com/halake.koshigaya/ )
- 11月11日(金) は、職場で予定があるので行けないです！
- 11月15日(火) は、残業ありです…

あと、定時であがっても 19 時 10 分に日比谷線神谷町なので、ちゃんとやるなら午後休とるよー

**Comment by SakaiYuki** [comment]
> gsアカデミーの課題ではここまで作った！

ログインしていないから見られなかった！

**Comment by GS05-43-MatsumuraYu** [comment]
午後休取ってまでも、とかホンマにありがとう！シャープ開発者とは雲泥の差やで。
午後休とるなら場所はnanolab@秋葉原でいいと思うよー。日程は酒井くんにあわすわ。今んとこ俺は来週月火が無理ですー

**Comment by GS05-43-MatsumuraYu** [comment]
午後休の取得タイミングだけど17(木)か18日(金)とか、どうかな？

**Comment by SakaiYuki** [comment]
> 午後休の取得タイミングだけど17(木)か18日(金)とか、どうかな？

ええよー

> ほんだら17日(木)でお願いします！

**Comment by SakaiYuki** [comment]
https://github.com/GS05-43-MatsumuraYu/kadai/issues/1#issuecomment-257213203 の段階で以下の仮設計でした。

> 1. GND
> 2. signal (analog voltage)
> 3. Vcc

しかし、 TANITA のキッチンスケールはアンプも内蔵した IC に、直接ひずみゲージの計測結果を入れており、取り出せる信号が非常に微小。 Arduino の 10 bit A/D で計測するには、計装アンプがやはり必要でした。

以下のように設計します。

```
＋－－＋
｜　　｜←キッチンスケール
＋－－＋
＋－－＋
||||
|||| ← 4本の線（紫： 3.3 V, 灰： GND、緑と青の電圧の差を測定する）
||||
＋－－＋
｜　　｜←中間基板（計装アンプ回路）
＋－－＋
|||
||| ← 3本の線（3.3 V, GND、アナログ電圧）
|||
＋－－＋
｜　　｜← Arduino
＋－－＋
```

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

> TANITA のキッチンスケールはアンプも内蔵した IC に、
> 直接ひずみゲージの計測結果を入れており、取り出せる信号が非常に微小。 
> Arduino の 10 bit A/D で計測するには、計装アンプがやはり必要でした。

なるほど、計測アンプが必要な件、了解です。

一方で、今の実装だと1つの調味料しか測れないという課題があって
それでには2方向考えられるんだけど、

　センサー1つでやる場合(今の状態)：置いたものに識別する情報を付与してサーバーに情報を送る
　例えば、デバイス側から物理ボタンを4つつけて、
　「1」を押して調味料を置く→10秒程待つ→キッチンスケールから離す

　センサーを4つにする：例えば圧力センサーを4つつけて、4種類の値を取得する。このやり方の場合、キッチンスケールは必要なくなる？かもしれない。
　
　他にやり方ありそうかな？

**Comment by SakaiYuki** [comment]
> ほんだら17日(木)でお願いします！

了解です！

> 1つの調味料しか測れないという課題

課題は明確だけど、「何を解決しようとする上での課題なのか」が明らかでないと、次の手がとれないな…
企画案を見てみたけど、その後アップデートがありそうなので、それを待ちます。
4 つ、測れればよいのかな？

> ＯＫ！

**Comment by GS05-43-MatsumuraYu** [comment]
[企画案(NEW).pdf](https://github.com/GS05-43-MatsumuraYu/kadai/files/593449/NEW.pdf)
]こんな感じ・・・か。

**Comment by GS05-43-MatsumuraYu** [comment]
ひとまず下記サイトを参考にコードを書いてみました。
https://github.com/GS05-43-MatsumuraYu/kadai/blob/master/Analog_Multiplexer.ino

参考サイト：http://d.hatena.ne.jp/hiko4415/20120627/1340806901
圧力センサーの２つ目をつけたいんだけど、付け方を教えてもらっていい?

**Comment by SakaiYuki** [comment]
## Arduino と センサ部とのインターフェイス設計

前回の作業で、更新された設計を確認します。基本は

```
○←圧力センサ
|| ← 2本の線（3.3 V, 計測点）
＋－－＋
｜　　｜←中間回路（マルチプレクサ回路）
＋－－＋
||||| ← 5本の線（3.3 V, GND、アナログ電圧、センサ選択*2）
＋－－＋
｜　　｜← Arduino
＋－－＋
```

で、

```
○←圧力センサ
|| ← 2本の線（3.3 V, 計測点）
```

の部分が 4 セットある設計です

**Comment by SakaiYuki** [comment]
今からコードみます！

**Comment by SakaiYuki** [comment]
> 圧力センサーの２つ目をつけたいんだけど、付け方を教えてもらっていい?

その前に、  https://github.com/GS05-43-MatsumuraYu/kadai/blob/master/Analog_Multiplexer.ino が想定通り動かないと、接続が間違っているのかどうかのデバッグができず、効率が悪いので、 #3 を起票して、修正をします
